spring:
  application:
    name: ms-users
  security:
    oauth2:
      client:
        registration:
          keycloak-lothlorien:
            authorization-grant-type: client_credentials
            client-id: non-standard-silverlode-client
            client-secret: shj6Ixu6hrWffvF89fubJhWmBfNiWOOs
            scope:
              - openid
        provider:
          keycloak-lothlorien:
            token-uri: http://localhost:8080/realms/Lothlorien/protocol/openid-connect/token

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081

users:
  elves:
    keycloak-lothlorien:
      serverUrl: http://localhost:8080
      clientId: non-standard-silverlode-client
      clientSecret: shj6Ixu6hrWffvF89fubJhWmBfNiWOOs
      realm: Lothlorien